using Homeji.Domain.Enums;

namespace Homeji.Application.DTOs.RentalPosts;

public sealed record RentalPostDto(
    Guid Id,
    Guid OwnerId,
    RentalPostType Type,
    RentalPostStatus Status,
    string Title,
    string Description,
    decimal Price,
    decimal Deposit,
    decimal Area,
    string Address,
    decimal Latitude,
    decimal Longitude,
    IReadOnlyCollection<string> Amenities,
    IReadOnlyCollection<RentalPostMediaDto> Media,
    int ViewCount,
    int SaveCount,
    decimal ElectricityPrice,
    decimal WaterPrice,
    decimal InternetPrice,
    int MaxOccupants,
    int AvailableSlots,
    string? HouseRules,
    DateOnly? AvailableFrom,
    RoomTransferKind? TransferKind,
    DateOnly? OriginalLeaseEndsOn,
    decimal PassFee,
    string? TransferReason,
    bool OwnerConsentConfirmed,
    string? OwnerConsentContact,
    DateTimeOffset? OwnerConsentVerifiedAt,
    string? ModerationReason,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    string? OwnerDisplayName = null,
    string? OwnerPhone = null,
    string? OwnerAvatarPath = null,
    bool IsOwnerVerified = false,
    bool IsOwnerPremium = false,
    string? OwnerBadge = null);
