// <auto-generated />
using System;
using Homeji.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Homeji.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260714233449_AddWalletFoodMarketplace")]
    partial class AddWalletFoodMarketplace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Homeji.Domain.Entities.BadWord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_bad_words");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("ux_bad_words_value");

                    b.ToTable("bad_words", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.ChatConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_conversations");

                    b.HasIndex("UserId", "UpdatedAt")
                        .HasDatabaseName("ix_chat_conversations_user_updated_at");

                    b.ToTable("chat_conversations", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Sender")
                        .HasColumnType("integer")
                        .HasColumnName("sender");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_chat_messages_conversation_created_at");

                    b.ToTable("chat_messages", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.LandlordVerificationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId", "CreatedAt");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("landlord_verification_requests", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.MarketplaceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AgreedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FundsReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarketplacePostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("PickupAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PlatformFeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PlatformFeeRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SellerNetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId", "CreatedAt");

                    b.HasIndex("SellerId", "CreatedAt");

                    b.HasIndex("MarketplacePostId", "BuyerId", "Status");

                    b.ToTable("marketplace_orders", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.MarketplacePost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("available_quantity");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("description");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<Guid?>("LinkedRentalPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_rental_post_id");

                    b.Property<int>("ListingType")
                        .HasColumnType("integer")
                        .HasColumnName("listing_type");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<int?>("PreparationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("preparation_minutes");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_quantity");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_marketplace_posts");

                    b.HasIndex("LinkedRentalPostId")
                        .HasDatabaseName("ix_marketplace_posts_linked_rental_post_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_marketplace_posts_seller_id");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_marketplace_posts_status_updated");

                    b.HasIndex("Status", "Latitude", "Longitude")
                        .HasDatabaseName("ix_marketplace_posts_map_search");

                    b.ToTable("marketplace_posts", "homeji", t =>
                        {
                            t.HasCheckConstraint("ck_marketplace_posts_price", "price > 0");

                            t.HasCheckConstraint("ck_marketplace_posts_stock", "available_quantity >= 0 AND reserved_quantity >= 0");
                        });
                });

            modelBuilder.Entity("Homeji.Domain.Entities.MarketplacePostMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MarketplacePostId")
                        .HasColumnType("uuid")
                        .HasColumnName("marketplace_post_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_marketplace_post_media");

                    b.HasIndex("MarketplacePostId", "SortOrder")
                        .HasDatabaseName("ix_marketplace_post_media_post_sort");

                    b.HasIndex("MarketplacePostId", "Url")
                        .IsUnique()
                        .HasDatabaseName("ux_marketplace_post_media_post_url");

                    b.ToTable("marketplace_post_media", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.MarketplaceSellerSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("marketplace_seller_subscriptions", "homeji", t =>
                        {
                            t.HasCheckConstraint("ck_marketplace_seller_subscription_commission", "\"CommissionRate\" > 0 AND \"CommissionRate\" < 1");

                            t.HasCheckConstraint("ck_marketplace_seller_subscription_price", "\"Price\" > 0");
                        });
                });

            modelBuilder.Entity("Homeji.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("RecipientId", "IsRead", "CreatedAt")
                        .HasDatabaseName("ix_notifications_recipient_unread_created");

                    b.ToTable("notifications", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Deeplink")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("deeplink");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_transaction_id");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("order_code");

                    b.Property<string>("PackageCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("package_code");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("payment_url");

                    b.Property<string>("ProviderMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("provider_message");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<string>("QrCode")
                        .HasColumnType("text")
                        .HasColumnName("qr_code");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("qr_code_url");

                    b.Property<string>("QrDataUrl")
                        .HasColumnType("text")
                        .HasColumnName("qr_data_url");

                    b.Property<string>("RawProviderPayload")
                        .HasColumnType("text")
                        .HasColumnName("raw_provider_payload");

                    b.Property<string>("RequestId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("request_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_transactions");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_transactions_order_code");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_payment_transactions_request_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payment_transactions_user_id");

                    b.ToTable("payment_transactions", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.PostConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipantAId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ParticipantALastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipantBId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ParticipantBLastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("SubjectType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantAId", "UpdatedAt");

                    b.HasIndex("ParticipantBId", "UpdatedAt");

                    b.HasIndex("SubjectType", "SubjectId", "ParticipantAId", "ParticipantBId")
                        .IsUnique();

                    b.ToTable("post_conversations", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.PostMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "SentAt");

                    b.ToTable("post_messages", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RentalPost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<decimal>("Area")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("area");

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("date")
                        .HasColumnName("available_from");

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("integer")
                        .HasColumnName("available_slots");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Deposit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("deposit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<decimal>("ElectricityPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("electricity_price");

                    b.Property<string>("HouseRules")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("house_rules");

                    b.Property<decimal>("InternetPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("internet_price");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<int>("MaxOccupants")
                        .HasColumnType("integer")
                        .HasColumnName("max_occupants");

                    b.Property<string>("ModerationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("moderation_reason");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("SaveCount")
                        .HasColumnType("integer")
                        .HasColumnName("save_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.Property<decimal>("WaterPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("water_price");

                    b.HasKey("Id")
                        .HasName("pk_rental_posts");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_rental_posts_owner_id");

                    b.HasIndex("Price")
                        .HasDatabaseName("ix_rental_posts_price");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_rental_posts_status");

                    b.HasIndex("Status", "Latitude", "Longitude")
                        .HasDatabaseName("ix_rental_posts_map_search");

                    b.ToTable("rental_posts", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RentalPostAmenity", b =>
                {
                    b.Property<Guid>("RentalPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("rental_post_id");

                    b.Property<string>("Code")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.HasKey("RentalPostId", "Code")
                        .HasName("pk_rental_post_amenities");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_rental_post_amenities_code");

                    b.ToTable("rental_post_amenities", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RentalPostMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bucket");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("boolean")
                        .HasColumnName("is_thumbnail");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer")
                        .HasColumnName("media_type");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<Guid>("RentalPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("rental_post_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_rental_post_media");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("ux_rental_post_media_path");

                    b.HasIndex("RentalPostId")
                        .HasDatabaseName("ix_rental_post_media_post_id");

                    b.ToTable("rental_post_media", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RentalReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AccuracyRating")
                        .HasColumnType("integer")
                        .HasColumnName("accuracy_rating");

                    b.Property<int?>("AmenitiesRating")
                        .HasColumnType("integer")
                        .HasColumnName("amenities_rating");

                    b.Property<int?>("CleanlinessRating")
                        .HasColumnType("integer")
                        .HasColumnName("cleanliness_rating");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("LandlordRating")
                        .HasColumnType("integer")
                        .HasColumnName("landlord_rating");

                    b.Property<int?>("LocationRating")
                        .HasColumnType("integer")
                        .HasColumnName("location_rating");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("RentalPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("rental_post_id");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<int?>("SecurityRating")
                        .HasColumnType("integer")
                        .HasColumnName("security_rating");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("ValueRating")
                        .HasColumnType("integer")
                        .HasColumnName("value_rating");

                    b.HasKey("Id")
                        .HasName("pk_rental_reviews");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("ix_rental_reviews_reviewer_id");

                    b.HasIndex("RentalPostId", "ReviewerId")
                        .IsUnique()
                        .HasDatabaseName("ux_rental_reviews_post_reviewer");

                    b.HasIndex("RentalPostId", "UpdatedAt")
                        .HasDatabaseName("ix_rental_reviews_post_updated");

                    b.ToTable("rental_reviews", "homeji", t =>
                        {
                            t.HasCheckConstraint("ck_rental_reviews_rating", "rating >= 1 AND rating <= 5");
                        });
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RentalWantedPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AmenityCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("DesiredMoveInDate")
                        .HasColumnType("date");

                    b.Property<decimal>("MaxBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("OccupantCount")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredArea")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId", "CreatedAt");

                    b.HasIndex("Status", "PreferredArea", "MaxBudget");

                    b.ToTable("rental_wanted_posts", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution_note");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_reports_status");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_reports_target");

                    b.ToTable("reports", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RoommateConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FirstParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_participant_id");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<Guid>("RentalPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("rental_post_id");

                    b.Property<Guid>("SecondParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("second_participant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roommate_conversations");

                    b.HasIndex("InvitationId")
                        .IsUnique()
                        .HasDatabaseName("ux_roommate_conversations_invitation_id");

                    b.HasIndex("RentalPostId")
                        .HasDatabaseName("ix_roommate_conversations_rental_post_id");

                    b.HasIndex("FirstParticipantId", "UpdatedAt")
                        .HasDatabaseName("ix_roommate_conversations_first_updated");

                    b.HasIndex("SecondParticipantId", "UpdatedAt")
                        .HasDatabaseName("ix_roommate_conversations_second_updated");

                    b.ToTable("roommate_conversations", "homeji", t =>
                        {
                            t.HasCheckConstraint("ck_roommate_conversations_distinct_participants", "first_participant_id <> second_participant_id");
                        });
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RoommateInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<Guid>("RentalPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("rental_post_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roommate_invitations");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_roommate_invitations_receiver_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_roommate_invitations_sender_id");

                    b.HasIndex("RentalPostId", "SenderId", "ReceiverId", "Status")
                        .HasDatabaseName("ix_roommate_invitations_pending_lookup")
                        .HasFilter("status = 1");

                    b.ToTable("roommate_invitations", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RoommateMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_roommate_messages");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_roommate_messages_sender_id");

                    b.HasIndex("ConversationId", "SentAt")
                        .HasDatabaseName("ix_roommate_messages_conversation_sent");

                    b.ToTable("roommate_messages", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.SavedPost", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RentalPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("rental_post_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "RentalPostId")
                        .HasName("pk_saved_posts");

                    b.HasIndex("RentalPostId")
                        .HasDatabaseName("ix_saved_posts_rental_post_id");

                    b.ToTable("saved_posts", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourcePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAt");

                    b.HasIndex("UserId", "Type", "OccurredAt");

                    b.ToTable("user_activities", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_path");

                    b.Property<string>("ContactAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contact_address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<int>("LandlordVerificationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("landlord_verification_status");

                    b.Property<decimal?>("MaxBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_budget");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_completed");

                    b.Property<int>("PetPreference")
                        .HasColumnType("integer")
                        .HasColumnName("pet_preference");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredArea")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("preferred_area");

                    b.Property<string>("RentalNeed")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rental_need");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("School")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("school");

                    b.Property<int>("SleepHabit")
                        .HasColumnType("integer")
                        .HasColumnName("sleep_habit");

                    b.Property<int>("SmokingPreference")
                        .HasColumnType("integer")
                        .HasColumnName("smoking_preference");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("package_code");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("package_name");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_subscriptions");

                    b.HasIndex("PaymentTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_subscriptions_payment_transaction_id")
                        .HasFilter("payment_transaction_id IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_subscriptions_user_id");

                    b.HasIndex("UserId", "Tier", "Status", "StartedAt", "ExpiresAt")
                        .HasDatabaseName("ix_user_subscriptions_active_lookup");

                    b.ToTable("user_subscriptions", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.ViewingAppointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RentalPostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.HasIndex("RequesterId", "CreatedAt");

                    b.HasIndex("RentalPostId", "RequesterId", "Status");

                    b.ToTable("viewing_appointments", "homeji");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.WalletAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalDeposited")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalEarned")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.ToTable("wallet_accounts", "homeji", t =>
                        {
                            t.HasCheckConstraint("ck_wallet_accounts_balance", "\"Balance\" >= 0");

                            t.HasCheckConstraint("ck_wallet_accounts_totals", "\"TotalDeposited\" >= 0 AND \"TotalSpent\" >= 0 AND \"TotalEarned\" >= 0");
                        });
                });

            modelBuilder.Entity("Homeji.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WalletUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletUserId", "CreatedAt");

                    b.HasIndex("WalletUserId", "Kind", "ReferenceId")
                        .IsUnique();

                    b.ToTable("wallet_transactions", "homeji", t =>
                        {
                            t.HasCheckConstraint("ck_wallet_transactions_amount", "\"Amount\" <> 0");
                        });
                });

            modelBuilder.Entity("Homeji.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.ChatConversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.LandlordVerificationRequest", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.MarketplaceOrder", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.MarketplacePost", null)
                        .WithMany()
                        .HasForeignKey("MarketplacePostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.MarketplacePost", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.RentalPost", null)
                        .WithMany()
                        .HasForeignKey("LinkedRentalPostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_marketplace_posts_linked_rental_posts");

                    b.HasOne("Homeji.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_marketplace_posts_sellers");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.MarketplacePostMedia", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.MarketplacePost", null)
                        .WithMany("Media")
                        .HasForeignKey("MarketplacePostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.MarketplaceSellerSubscription", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.PostMessage", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.PostConversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RentalPostAmenity", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.RentalPost", null)
                        .WithMany("Amenities")
                        .HasForeignKey("RentalPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RentalPostMedia", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.RentalPost", null)
                        .WithMany("Media")
                        .HasForeignKey("RentalPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RentalReview", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.RentalPost", null)
                        .WithMany()
                        .HasForeignKey("RentalPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rental_reviews_rental_posts");

                    b.HasOne("Homeji.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rental_reviews_user_profiles");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RentalWantedPost", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RoommateConversation", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("FirstParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roommate_conversations_first_participant");

                    b.HasOne("Homeji.Domain.Entities.RoommateInvitation", null)
                        .WithOne()
                        .HasForeignKey("Homeji.Domain.Entities.RoommateConversation", "InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roommate_conversations_invitations");

                    b.HasOne("Homeji.Domain.Entities.RentalPost", null)
                        .WithMany()
                        .HasForeignKey("RentalPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roommate_conversations_rental_posts");

                    b.HasOne("Homeji.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("SecondParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roommate_conversations_second_participant");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RoommateMessage", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.RoommateConversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roommate_messages_conversations");

                    b.HasOne("Homeji.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roommate_messages_senders");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.UserActivity", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.ViewingAppointment", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.RentalPost", null)
                        .WithMany()
                        .HasForeignKey("RentalPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.WalletAccount", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.UserProfile", null)
                        .WithOne()
                        .HasForeignKey("Homeji.Domain.Entities.WalletAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Homeji.Domain.Entities.WalletAccount", null)
                        .WithMany()
                        .HasForeignKey("WalletUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeji.Domain.Entities.ChatConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.MarketplacePost", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Homeji.Domain.Entities.RentalPost", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
